language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: TQprAZAn7S7hRV49kzM161M3oYFLFj3l0yMBB6yFNlFa8+Ly8pFSeqPiQNhrMj67T1FRY5D56aP/8GQ+Qz2jaJQMmCoHQ77HaE6S3VN+hk0hdKNqsHU137AAQ3nwBzEvVMNp6A4Hq6KGfJrlJNpM37dLgHmWZJwDaqVEFpWa+BWEnWIUIzZXx6EEJqD9pPf2zwyQVXhV37TCvEir2TP9+xsKlB0Y5/N9fRSsX2Kwj00fL6oXWUn0sgkZhx+MTpbVgFOG+rLZAo1uBZ1jJPS5mKVPw23lTOL6ClklgWW+Up8vexMbx1KhFCMujqcMJJkJofw4LNDO1yD6nriPIU6ZbRS6wTHBeeFRDuiLLEdffesB57RAZhjbc+qZrCoAFz/a0igRp9JphdzOmOayKBSfMpX/KAoC3IravpZHEc2Cp/fb8bb5gUZFdfpKY4isrIvtILOsWz6jiV1AKJ19zOTtwLjr2qbWsj9E2g1uk9uKqmRsHyfcjmmxPSMJK6GuTP2/70nzkWpjGLAQCn+uwBDjNyfljBoGevJ5rK4Jf8UStXE+rRNHYrk1Q8LE3sUoWP9LquvpgQQGNqtlEDzYx1TBsNs/WgbHF+557x4k9vZQxMub2q1VP0yrPdKDngxCA+c0MFB+iIaM0LCo7H2WA9XqdjTLYb81RP1lFTIFRKJOaTA=
  app: leaderboard-co
  skip_cleanup: true
notifications:
  email: false
script:
- npm test
